CREATE TABLE IF NOT EXISTS invoices (
    id TEXT PRIMARY KEY NOT NULL,

    nbmst TEXT,
    khmshdon INTEGER,
    khhdon TEXT,
    shdon INTEGER,
    cqt TEXT,
    cttkhac TEXT,
    dvtte TEXT,
    hdon TEXT,
    hsgcma TEXT,
    hsgoc TEXT,
    hthdon INTEGER,
    htttoan TEXT,
    idtbao TEXT,
    khdon INTEGER,
    khhdgoc TEXT,
    khmshdgoc TEXT,
    lhdgoc TEXT,
    mhdon TEXT,
    mtdiep TEXT,
    mtdtchieu TEXT,
    nbdchi TEXT,
    chma TEXT,
    chten TEXT,
    nbhdktngay TEXT,
    nbhdktso TEXT,
    nbhdso TEXT,
    nblddnbo TEXT,
    nbptvchuyen TEXT,
    nbstkhoan TEXT,
    nbten TEXT,
    nbtnhang TEXT,
    nbtnvchuyen TEXT,
    nbttkhac TEXT,
    ncma TEXT,
    ncnhat TEXT,
    ngcnhat TEXT,
    nky TEXT,
    nmdchi TEXT,
    nmmst TEXT,
    nmstkhoan TEXT,
    nmten TEXT,
    nmtnhang TEXT,
    nmtnmua TEXT,
    nmttkhac TEXT,
    ntao TEXT,
    ntnhan TEXT,
    pban TEXT,
    ptgui INTEGER,
    shdgoc INTEGER,
    tchat INTEGER,
    tdlap TEXT,
    tgia DOUBLE PRECISION,
    tgtcthue DOUBLE PRECISION,
    tgtthue DOUBLE PRECISION,
    tgtttbchu TEXT,
    tgtttbso DOUBLE PRECISION,
    thdon TEXT,
    thlap TEXT,
    thttlphi TEXT,
    thttltsuat TEXT,
    tlhdon TEXT,
    ttcktmai DOUBLE PRECISION,
    tthai INTEGER,
    ttkhac TEXT,
    tttbao TEXT,
    ttttkhac TEXT,
    ttxly INTEGER,
    tvandnkntt TEXT,
    mhso TEXT,
    ladhddt TEXT,
    mkhang TEXT,
    nbsdthoai TEXT,
    nbdctdtu TEXT,
    nbfax TEXT,
    nbwebsite TEXT,
    nbcks TEXT,
    nmsdthoai TEXT,
    nmdctdtu TEXT,
    nmcmnd TEXT,
    nmcks TEXT,
    bhphap TEXT,
    hddunlap TEXT,
    gchdgoc TEXT,
    tbhgtngay TEXT,
    bhpldo TEXT,
    bhpcbo TEXT,
    bhpngay TEXT,
    tdlhdgoc TEXT,
    tgtphi DOUBLE PRECISION,
    unhiem TEXT,
    mstdvnunlhdon TEXT,
    tdvnunlhdon TEXT,
    nbmdvqhnsach TEXT,
    nbsqdinh TEXT,
    nbncqdinh TEXT,
    nbcqcqdinh TEXT,
    nbhtban TEXT,
    nmmdvqhnsach TEXT,
    nmddvchden TEXT,
    nmtgvchdtu TEXT,
    nmtgvchdden TEXT,
    nbtnban TEXT,
    dcdvnunlhdon TEXT,
    dksbke TEXT,
    dknlbke TEXT,
    thtttoan TEXT,
    msttcgp TEXT,
    cqtcks TEXT,
    gchu TEXT,
    kqcht TEXT,
    hdntgia TEXT,
    tgtkcthue TEXT,
    tgtkhac TEXT,
    nmshchieu TEXT,
    nmnchchieu TEXT,
    nmnhhhchieu TEXT,
    nmqtich TEXT,
    ktkhthue TEXT,
    qrcode TEXT,
    ttmstten TEXT,
    ladhddtten TEXT,
    hdxkhau TEXT,
    hdxkptquan TEXT,
    hdgktkhthue TEXT,
    hdonLquans TEXT,
    tthdclquan TEXT,
    pdndungs TEXT,
    hdtbssrses TEXT,
    hdTrung TEXT,
    isHDTrung TEXT,

    LastDownloadedDate TIMESTAMP NOT NULL DEFAULT now(),
    DetailStatus INTEGER DEFAULT 0,
    DetailRetryCount INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_invoices_tdlap ON invoices (tdlap);
CREATE INDEX IF NOT EXISTS idx_invoices_nbmst ON invoices (nbmst);
